cant run application, more details: ` Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/PropertyNamingStrategy$SnakeCaseStrategy 	at io.dropwizard.jackson.AnnotationSensitivePropertyNamingStrategy.<init>(AnnotationSensitivePropertyNamingStrategy.java:22) 	at io.dropwizard.jackson.Jackson.configure(Jackson.java:64) 	at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:25) 	at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64) 	at io.dropwizard.Application.run(Application.java:82) 	at com.dk.trender.TrenderApplication.main(TrenderApplication.java:149) Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 6 more `